baseURL = "https://MattWindsor91.github.io/"
languageCode = "en-gb"
title = "Matt Windsor's Web Thingy"
theme = "aether"
author = "Matt Windsor"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  brand = "Matt Windsor"
  description = "Being a person who does verification and compiler stuff."
  twitter = "MattWindsor91"
